version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dpl_db
      POSTGRES_USER: dpl_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init:/opt/init
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: dpl_user
      DB_PASSWORD: password
      DB_DB: dpl_db
      DB_PORT: 5432
      DB_HOST: db
