version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: pgdb
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d dpl_db -U dpl_user" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3000
      DB_USER: dpl_user
      DB_PASSWORD: password
      DB_DB: dpl_db
      DB_PORT: 5432
      DB_HOST: localhost
