version: '3'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_USER: dpl_user
      DB_PASSWORD: password
      DB_DB: dpl_db
      PORT: 5432
  db:
    image: postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dpl_db
      POSTGRES_USER: dpl_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init:/opt/init
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/