version: '3'
services:
  server:
    image: postgrest/postgrest
    container_name: postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://dpl_user:password@db:5432/dpl_db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - db
  db:
    image: postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dpl_db
      POSTGRES_USER: dpl_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init:/opt/init
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/